# Generated by Django 4.2.20 on 2025-05-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='할일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('end_at', models.DateTimeField(auto_now_add=True, verbose_name='마감일')),
                ('is_completed', models.BooleanField(verbose_name='종료 여부')),
            ],
        ),
    ]
