# Generated by Django 4.2.20 on 2025-05-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateField(verbose_name='마감일'),
        ),
    ]
