# Generated by Django 4.2.20 on 2025-05-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_at_alter_task_end_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='start_at',
        ),
    ]
