# Generated by Django 4.2.20 on 2025-04-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('description', models.TextField(verbose_name='이미지 설명')),
                ('uploader', models.TextField(verbose_name='업로드한 사람')),
                ('created_at', models.DateTimeField(verbose_name='업로드일')),
            ],
        ),
    ]
